version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: build image
          command: |
            docker build -t "$DOCKER_REPO:latest" .
      - deploy:
          name: upload to dockerhub
          command: |
            if [[ -n "$DOCKER_USER" ]]; then
              docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
              docker push "$DOCKER_REPO:latest"
            fi
